SHELL := /bin/bash
.PHONY: help verify test-git dist check-dist clean

help:
	@echo ""
	@echo "  AgenticDev"
	@echo ""
	@echo "  Install / Instalace"
	@echo "    sudo ./install-vps.sh          server"
	@echo "    bash agenticdev-install-mac.sh      client (generated by the server)"
	@echo ""
	@echo "  Development / Vývoj"
	@echo "    make verify      check the repo tree / ověří strom repa"
	@echo "    make test-git    exercise agenticdev-git on a temp repo"
	@echo "    make dist        build dist/agenticdev-install-vps.sh"
	@echo "    make check-dist  build, then run the artifact's own --check"
	@echo "    make clean       remove dist/"
	@echo ""

verify:
	@./tools/verify-tree.sh

test-git:
	@bash tools/test-git.sh

dist:
	@bash tools/mk-dist.sh

check-dist: dist
	@echo "▸ Ověřuji vydaný artefakt"
	@bash dist/agenticdev-install-vps.sh --check

clean:
	@rm -rf dist
	@echo "  ✓ dist/ smazán"
