SHELL := /bin/bash
.PHONY: help verify test test-git test-broker dist check-dist clean preflight smoke

help:
	@echo ""
	@echo "  AgenticDev"
	@echo ""
	@echo "  Install / Instalace"
	@echo "    make preflight   check a fresh VPS before installing / před instalací"
	@echo "    sudo ./install-vps.sh          server"
	@echo "    make smoke       verify a deployment end to end / po instalaci"
	@echo "    bash agenticdev-install-mac.sh      client (generated by the server)"
	@echo ""
	@echo "  Development / Vývoj"
	@echo "    make verify      check the repo tree / ověří strom repa"
	@echo "    make test-git    exercise agenticdev-git on a temp repo"
	@echo "    make dist        build dist/agenticdev-install-vps.sh"
	@echo "    make check-dist  build, then run the artifact's own --check"
	@echo "    make clean       remove dist/"
	@echo ""

preflight:
	@bash tools/preflight-vps.sh

smoke:
	@bash tools/smoke-vps.sh

verify:
	@./tools/verify-tree.sh

test-git:
	@bash tools/test-git.sh

test-broker:
	@python3 -m unittest discover -s tests -v

test: verify test-git test-broker

dist:
	@bash tools/mk-dist.sh

check-dist: dist
	@echo "▸ Ověřuji vydaný artefakt"
	@bash dist/agenticdev-install-vps.sh --check

clean:
	@rm -rf dist
	@echo "  ✓ dist/ smazán"
